import type {
  TechStackCategory,
} from "./siteContent";

export const techStackCategories: TechStackCategory[] = [
  {
    id: "core",
    title: "Core Geospatial Python",
    description: "The Python tools that anchor practical vector analysis, modelling, and open geospatial workflows.",
    items: [
      "JupyterLab",
      "Pixi",
      "pyproj",
      "GeoPandas",
      "pyogrio",
      "Shapely",
      "pandas",
      "libpysal",
      "esda",
      "pointpats",
      "h3-py",
      "contextily",
      "tobler",
      "pyinterpolate",
      "statsmodels",
      "mgwr",
      "scikit-learn",
      "osmnx",
    ],
  },
  {
    id: "raster",
    title: "Raster & Cloud-Native EO",
    description: "The cloud-native raster, imagery, and data-layout tooling behind modern earth observation delivery.",
    items: [
      "Xarray",
      "rioxarray",
      "Rasterio",
      "Datashader",
      "geocube",
      "xvec",
      "STAC",
      "COG",
      "Zarr",
      "GeoParquet",
      "DuckDB",
      "Dask",
      "Pangeo ecosystem",
      "Azure Blob Storage",
      "Azure Container Apps",
      "Azure Functions",
    ],
  },
  {
    id: "frontend",
    title: "Front-End & Interactive Maps",
    description: "Interfaces for exploration, decision support, and live operational views.",
    items: ["Power BI", "Tableau", "Leaflet", "D3.js", "OpenLayers", "React", "Angular"],
  },
  {
    id: "realtime",
    title: "Real-Time & Event-Driven",
    description: "Streaming infrastructure for IoT, live feeds, and event-driven geo-spatial systems.",
    items: ["Kafka", "WebSockets", "Azure Event Hub", "Stream Analytics", "IoT Hub"],
  },
  {
    id: "apis",
    title: "APIs, Servers & Integration",
    description: "Open standards, service layers, and integration points for geospatial delivery.",
    items: [
      "OGC-compliant APIs",
      "STAC APIs",
      "FastAPI",
      "Flask",
      "Django",
      ".NET Core API",
      "Node.js",
      "Express.js",
      "Ruby",
      "Rails",
      "NGINX",
      "GeoServer",
    ],
  },
  {
    id: "analysis",
    title: "Analysis & ML",
    description: "Earth observation analysis, acceleration, and geospatial machine learning.",
    items: [
      "CUDA",
      "OpenGL",
      "RAPIDS",
      "C/C++",
      "Python",
      "cuDF",
      "TorchGeo",
      "Ktorch",
      "Hugging Face",
      "Spark",
      "Kafka",
      "GDAL",
      "ArcPy",
      "Google Earth Engine",
      "Unity 3D",
      "QGIS",
      "GRASS",
    ],
  },
  {
    id: "infrastructure",
    title: "Infrastructure & OS",
    description: "Cloud, containers, orchestration, and operating environments for resilient delivery.",
    items: [
      "CentOS / RHEL 9",
      "Ubuntu",
      "OpenSUSE",
      "Azure",
      "GCP",
      "OpenStack",
      "Podman",
      "Docker",
      "Kubernetes bare-metal",
      "OpenShift",
      "Rancher",
      "AKS",
      "EKS",
    ],
  },
  {
    id: "devsecops",
    title: "DevSecOps",
    description: "Security, testing, monitoring, and delivery automation across the platform.",
    items: [
      "Ansible",
      "Terraform",
      "Qualys",
      "SonarCloud",
      "ZAP",
      "AquaSec",
      "SELinux",
      "Azure Security Center",
      "Prometheus",
      "Grafana",
      "Azure DevOps",
      "GitLab",
      "Selenium",
      "Pytest",
    ],
  },
  {
    id: "databases",
    title: "Databases & Geo-Databases",
    description: "Spatial persistence, delivery layers, and query systems for geo-data applications.",
    items: [
      "Redis",
      "Azure Front Door",
      "PostgreSQL",
      "PostGIS",
      "MongoDB",
      "Cassandra",
      "Hadoop",
      "SQL",
      "SPARQL",
    ],
  },
  {
    id: "warehouse",
    title: "Data Persistence & Next-Gen Data Warehouse",
    description: "Cloud storage, orchestration, and modern geospatial data formats.",
    items: [
      "Azure Data Lake",
      "S3",
      "Databricks",
      "Airflow",
      "BigQuery",
      "Synapse",
      "Cortex",
      "STAC metadata",
      "GeoTIFF",
      "GeoArrow",
      "GeoParquet",
      "FlatGeobuf",
      "PMTiles",
      "COG",
      "Zarr",
      "COPC",
      "RDF"
    ],
  },
];
